### ISSUE TITLE
make doc fails. First error: error[E0463]: can't find crate for `core`

### ISSUE THREAD

**Issue by kimphillamd** [AMDESE/linux-svsm#1]
Full log attached.  Ubuntu 22.04.1 LTS.
[log.txt](https://github.com/AMDESE/linux-svsm/files/9449727/log.txt)

**Comment by Zildj1an** [comment]
So, what happened is that make doc also requires make prereq. That wasn't clear in the README, or enforced in the Makefile. I just committed [changes](https://github.com/AMDESE/linux-svsm/commit/80b76816185f337c58b30f5e2b4f27bf2103e204) to fix this. Thanks for bringing this to our attention @kimphillamd.
