### ISSUE TITLE
How to capture the outputs of serial_out in the terminal?

### ISSUE THREAD

**Issue by mbs0221** [AMDESE/linux-svsm#29]
Hello, everyone. Here comes a problem!

I noticed that the `prints` macro can be used to write a string to the serial output. However, after running guest-os with `linux-svsm` support successfully, I can not find the outputs of `prints` macro in the complete booting logs on the screen. The command line to boot the guest-os is as following.

```
sudo ./launch-qemu.sh -hda guest.raw -sev-snp -svsm svsm.bin
```

So how can I enable the serial output of the Qemu, such that I can capture the prints from svsm in the terminal. Any help would be appreciated.

**Comment by dubek** [comment]
@mbs0221 Did you build svsm with the `verbose` feature, as follows:

    FEATURES=verbose make

?

**Comment by mbs0221** [comment]
> @mbs0221 Did you build svsm with the `verbose` feature, as follows:
> 
> ```
> FEATURES=verbose make
> ```
> 
> ?

Oh, I just noticed this command line in the README and didn't add FEATURES=verbose in the previous building process. Many thanks for your timely help!

**Comment by Zildj1an** [comment]
You might also want to add a `breakpoint()` (from [util.rs](https://github.com/AMDESE/linux-svsm/blob/main/src/util/util.rs)) so your outputs don't get lost after your guest's booting log.
