### ISSUE TITLE
apic_id_for() returning `cpu_id`

### ISSUE THREAD

**Issue by haraldh** [AMDESE/linux-svsm#32]
https://github.com/AMDESE/linux-svsm/blob/f68a6c7e413abd0073803db255b8fd6afcb3703e/src/cpu/percpu.rs#L145

shouldn't this be 
```rust
            apic_id = (*p).apic_id;
```
?

**Comment by Zildj1an** [comment]
Yes, it should. Thanks for catching this bug. Would you like to author a pull request fixing it? If not that is fine, I can take care of it.

**Comment by haraldh** [comment]
https://github.com/AMDESE/linux-svsm/pull/33
