### ISSUE TITLE
Bugs with rust 1.71.0-nightly

### ISSUE THREAD

**Issue by dubek** [AMDESE/linux-svsm#51]
I updated my Rust toolchain:

```
$ cargo --version
cargo 1.71.0-nightly (de80432f0 2023-04-21)
```

Now I'm running into two problems (so far):

1. Feature `alloc_handler_error` no longer exists:

```
   Compiling linux_svsm v0.1.0 (/home/dov/linux-svsm)
error[E0557]: feature has been removed
  --> src/lib.rs:11:12
   |
11 | #![feature(alloc_error_handler)]
   |            ^^^^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: now handled by panic handler

error: cannot find attribute `alloc_error_handler` in this scope
    --> src/mem/alloc.rs:1145:3
     |
1145 | #[alloc_error_handler]
     |   ^^^^^^^^^^^^^^^^^^^
     |
     = note: `alloc_error_handler` is in scope, but it is a function, not an attribute

For more information about this error, try `rustc --explain E0557`.
error: could not compile `linux_svsm` (lib) due to 2 previous errors
```

It seems that the default implemenation of the alloc error is to panic, which is good for us (it'll call our custom panic handler). If I delete all mentions of alloc_error_handler, I can successfully build linux-svsm.

2. When I run linux-svsm, I get this:

```
Launching VM ...
  /tmp/cmdline.74246
char device redirected to /dev/pts/10 (label compat_monitor0)
> All 18 firmware config files read.
> Starting SMP for 7 APs:
-- AP 1/7 initialized.
-- AP 2/7 initialized.
-- AP 3/7 initialized.
-- AP 4/7 initialized.
-- AP 5/7 initialized.
-- AP 6/7 initialized.
-- AP 7/7 initialized.
PANIC!
panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0xffff8000ffffff6e', src/bios.rs:203:23
PANIC!
```

I haven't yet started debugging this (or tried to understand why this behaviour has changed).

**Comment by dubek** [comment]
This solves the second issue but not very beautiful:

```diff
diff --git a/src/bios.rs b/src/bios.rs
index 251d7ad..83cb0af 100644
--- a/src/bios.rs
+++ b/src/bios.rs
@@ -200,7 +200,8 @@ fn find_bios_guid_entry(bios_info: &mut BiosInfo, target_guid: Uuid) -> Option<u
 }

 unsafe fn __find_snp_section(bios_info: &mut BiosInfo, stype: u32, p: u64) -> Option<SnpSection> {
-    let offset: u64 = *(p as *const u32) as u64;
+    let offset_bytes: &[u8] = unsafe { slice::from_raw_parts(p as *const u8, 4) };
+    let offset: u64 = u32::from_le_bytes(offset_bytes.try_into().unwrap()) as u64;
     if offset > bios_info.size() {
         return None;
     }
```

**Comment by dubek** [comment]
Re: misaligned pointer: I tried a small program in both rust 1.69.0 (passes) an rust 1.70.0 (panics):
https://rust.godbolt.org/z/8jhG7Yrs1
if I add `-C opt-level=3` to the compiler flags in 1.70.0, it doesn't panic.

I tried compiling linux-svsm with `xargo build --release` but it still panics.

**Comment by dubek** [comment]
(and it looks like there's a [`core::ptr::read_unaligned`](https://doc.rust-lang.org/core/ptr/fn.read_unaligned.html) instead of my patch above.)

**Comment by dubek** [comment]
> I tried compiling linux-svsm with `xargo build --release` but it still panics.

Correction: it does solve the issue (removes the alignment check). To compile in release, you need both `xargo build --release` and set `TARGET := $(TARGET_DIR)/svsm-target/release` in Makefile.

**Comment by Zildj1an** [comment]
This looks good, do you want to PR it? I see our tests already failing for the same reason [here](https://github.com/AMDESE/linux-svsm/pull/50)
