### ISSUE TITLE
How to get the output of SVSM?

### ISSUE THREAD

**Issue by GToad** [AMDESE/linux-svsm#57]
Sorry for help. I'm trying to add code for SVSM, however, I cannot get the output from the terminal or QEMU cmdline generated by the RUST code, like:
```
prints!("Hello, new SVSM calls");
```
How can I get the output, or are there other debugging methods recommanded?

**Comment by tlendacky** [comment]
Be sure to specify FEATURES="verbose" on the make command line when building the SVSM.

Also, take a look at the coconut-svsm, as that will be where development is focused going forward.

**Comment by GToad** [comment]
> Be sure to specify FEATURES="verbose" on the make command line when building the SVSM.
> 
> Also, take a look at the coconut-svsm, as that will be where development is focused going forward.

Thank you so much! It worked.
