### ISSUE TITLE
ccp 0000:46:00.1: SEV-SNP support requires firmware version >= 1:51

### ISSUE THREAD

**Issue by aep** [AMDESE/linux-svsm#9]
i cant launch sev guests on this host kernel.

```
qemu-system-x86_64: sev_kvm_init: cbitpos check failed, host '51' requested '0'
qemu-system-x86_64: failed to initialize kvm: Operation not permitted
```

this is possibly related

```
root@yca7h:~/linux-svsm/scripts# dmesg | grep -i sev
[    0.541244] SEV-SNP: RMP table physical address 0x0000000035600000 - 0x0000000075bfffff
[   53.723301] ccp 0000:46:00.1: sev enabled
[   53.739626] ccp 0000:46:00.1: SEV-SNP support requires firmware version >= 1:51
[   53.752157] ccp 0000:46:00.1: SEV: failed to INIT error 0x1
[   53.752162] ccp 0000:46:00.1: SEV API:1.15 build:15
[   54.166212] SEV supported: 410 ASIDs
[   54.166212] SEV-ES and SEV-SNP supported: 99 ASIDs

```

firmware doesnt appear to be loaded at all. on another host with an upstream kernel i'm getting this dmesg 

```

root@sev-playground ~ # dmesg | grep firmware
[    0.158501] Spectre V2 : Enabling Speculation Barrier for firmware calls
[    0.611350] GHES: APEI firmware first mode is enabled by APEI bit.
[    4.723458] ccp 0000:44:00.1: firmware: failed to load amd/amd_sev_fam17h_model31h.sbin (-2)
[    4.723615] firmware_class: See https://wiki.debian.org/Firmware for information about missing firmware
[    4.723805] ccp 0000:44:00.1: firmware: failed to load amd/amd_sev_fam17h_model31h.sbin (-2)
[    4.724521] ccp 0000:44:00.1: firmware: direct-loading firmware amd/amd_sev_fam17h_model3xh.sbin
```

but  this kernel has no such messages

```
root@yca7h:/lib/firmware/amd# ls -l
-rw-r--r-- 1 root root  82688 Sep  8 11:33  amd_sev_fam19h_model0xh_1.51.03.esbin
-rw-r--r-- 1 root root  82688 Sep  8 11:33  amd_sev_fam19h_model0xh_1.51.03.sbin
-rw-r--r-- 1 root root 142857 Sep  8 18:59  amd_sev_fam19h_model0xh_1.51.03.zip
-rw-r--r-- 1 root root  14873 Sep  8 11:50 'Milan Release Notes.txt'

```

this is a 7443P

maybe this is related?

![2022-09-27-175731_797x602_scrot](https://user-images.githubusercontent.com/136926/192576095-e11d4a68-5709-414c-882b-331c38e1eb1e.png)

**Comment by tlendacky** [comment]
> i cant launch sev guests on this host kernel.
> 
> ```
> qemu-system-x86_64: sev_kvm_init: cbitpos check failed, host '51' requested '0'
> qemu-system-x86_64: failed to initialize kvm: Operation not permitted
> ```

Issue "modprobe cpuid" and see if that resolves this issue. There is currently a pull request to improve obtaining the encryption bit position that should be applied soon.

> 
> this is possibly related
> 
> ```
> root@yca7h:~/linux-svsm/scripts# dmesg | grep -i sev
> [    0.541244] SEV-SNP: RMP table physical address 0x0000000035600000 - 0x0000000075bfffff
> [   53.723301] ccp 0000:46:00.1: sev enabled
> [   53.739626] ccp 0000:46:00.1: SEV-SNP support requires firmware version >= 1:51
> [   53.752157] ccp 0000:46:00.1: SEV: failed to INIT error 0x1
> [   53.752162] ccp 0000:46:00.1: SEV API:1.15 build:15
> [   54.166212] SEV supported: 410 ASIDs
> [   54.166212] SEV-ES and SEV-SNP supported: 99 ASIDs
> ```
> 
> firmware doesnt appear to be loaded at all. on another host with an upstream kernel i'm getting this dmesg

It is loaded, it is just very old. See below for how the firmware file should be named, but if that doesn't resolve it, you may have to upgrade the BIOS to get a newer version of the firmware that will allow the download_firmware command to function properly.

> 
> ```
> 
> root@sev-playground ~ # dmesg | grep firmware
> [    0.158501] Spectre V2 : Enabling Speculation Barrier for firmware calls
> [    0.611350] GHES: APEI firmware first mode is enabled by APEI bit.
> [    4.723458] ccp 0000:44:00.1: firmware: failed to load amd/amd_sev_fam17h_model31h.sbin (-2)
> [    4.723615] firmware_class: See https://wiki.debian.org/Firmware for information about missing firmware
> [    4.723805] ccp 0000:44:00.1: firmware: failed to load amd/amd_sev_fam17h_model31h.sbin (-2)
> [    4.724521] ccp 0000:44:00.1: firmware: direct-loading firmware amd/amd_sev_fam17h_model3xh.sbin
> ```
> 
> but this kernel has no such messages
> 
> ```
> root@yca7h:/lib/firmware/amd# ls -l
> -rw-r--r-- 1 root root  82688 Sep  8 11:33  amd_sev_fam19h_model0xh_1.51.03.esbin
> -rw-r--r-- 1 root root  82688 Sep  8 11:33  amd_sev_fam19h_model0xh_1.51.03.sbin
> -rw-r--r-- 1 root root 142857 Sep  8 18:59  amd_sev_fam19h_model0xh_1.51.03.zip
> -rw-r--r-- 1 root root  14873 Sep  8 11:50 'Milan Release Notes.txt'
> ```
> 
> this is a 7443P

The amd_sev_fam19h_model0xh_1.51.03.sbin file should be copied from the zip file into /lib/firmware/amd/ as amd_sev_fam19h_model0xh.sbin

**Comment by aep** [comment]
> The amd_sev_fam19h_model0xh_1.51.03.sbin file should be copied from the zip file into /lib/firmware/amd/ as amd_sev_fam19h_model0xh.sbin

yes, that doesnt solve it

> you may have to upgrade the BIOS to get a newer version of the firmware

This is the latest vendor provided BIOS. As retail customers we have no influence on the vendors (asrock in this case).
Is there a list of boards that have the correct bios?

**Comment by tlendacky** [comment]
> > The amd_sev_fam19h_model0xh_1.51.03.sbin file should be copied from the zip file into /lib/firmware/amd/ as amd_sev_fam19h_model0xh.sbin
> 
> yes, that doesnt solve it

What kind of output did you get? (dmesg | egrep "ccp|SEV")

> 
> > you may have to upgrade the BIOS to get a newer version of the firmware
> 
> This is the latest vendor provided BIOS. As retail customers we have no influence on the vendors (asrock in this case). Is there a list of boards that have the correct bios?

Nothing that we keep. I would suggest contacting ASRock and see if they have some version available that might not be listed on their website?

**Comment by aep** [comment]
> Issue "modprobe cpuid" and see if that resolves this issue. There is currently a pull request to improve obtaining the encryption bit position that should be applied soon.

for some reason this solved the issue, and everything else is unrelated.
thanks. and sorry for not trying that first.

**Comment by tlendacky** [comment]
> [   53.752157] ccp 0000:46:00.1: SEV: failed to INIT error 0x1

This was an issue, but maybe with the correct naming of the firmware file allowed the download firmware command to succeed and fixed that. I would still be interested in seeing the output from dmesg | egrep "ccp|SEV"

**Comment by aep** [comment]
```

[    0.529480] SEV-SNP: RMP table physical address 0x0000000035600000 - 0x0000000075bfffff
[   53.399408] ccp 0000:46:00.1: enabling device (0000 -> 0002)
[   53.399540] ccp 0000:46:00.1: no command queues available
[   53.399589] ccp 0000:46:00.1: sev enabled
[   53.399590] ccp 0000:46:00.1: psp enabled
[   53.457179] ccp 0000:46:00.1: SEV firmware update successful
[   57.056955] ccp 0000:46:00.1: SEV-SNP API:1.51 build:3
[   57.064244] SEV supported: 410 ASIDs
[   57.064245] SEV-ES and SEV-SNP supported: 99 ASIDs
```

the guest boots now fine -sev-snp -svsm and the guest kernel indicates it recognizes the svsm.

btw how do i now get an attestation  report? this is the first time i'm trying SNP at all, and i'm a little lost how the AMDESE tools fit together. i think its AMDESE/sev-guest? but thats incompatible with ubuntu 22

**Comment by tlendacky** [comment]
> btw how do i now get an attestation report? this is the first time i'm trying SNP at all, and i'm a little lost how the AMDESE tools fit together. i think its AMDESE/sev-guest? but thats incompatible with ubuntu 22 (or just this guest kernel?)
> 
> ```
> firmware error 0x16
> ```
> 
> [AMDESE/sev-guest#26](https://github.com/AMDESE/sev-guest/issues/26)

I haven't worked with this before, hopefully someone from that project/repo answers soon. If not, I'll take a look at it in the next day or two.
